name: Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env
      
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install cdxgen
        run: npm install -g @cyclonedx/cdxgen

      - name: Install depscan
        run: pip install owasp-depscan

      - name: Generate SBOMs
        run: |
          cdxgen -t python .

      - name: Generate VDR
        run: |
          depscan --bom bom.json
          # move vdr enriched sbom to make it easier to grab as an artifact
          # if it doesn't exist then echo that for reference
          mv ./bom.vdr.json ./reports/bom.vdr.json || echo "No VDR was generated."

      - name: Store SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bom
          path: ./bom.json

      - name: Store VDR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vdr
          path: ./reports
